### ISSUE TITLE
Can not find home page in route

### ISSUE THREAD

**Issue by parthvaghelaHD** [sry1998/blogRender#10]
Home page route is not found. make it fix.

**Comment by parthvaghelaHD** [comment]
suppose that localhost://4000/ is as a home route. if home route is not find , and when user came and they can not find where is registration page or login page route so make it easier to understand for user. so add a one more rote as a home page , through user can access registration page and login page  !!

**Comment by sry1998** [comment]
You can just open the link from the terminal when server is started
